### ISSUE TITLE
"Clickbait" is a mass noun.

### ISSUE THREAD

**Issue by MichaelSynnott** [rahulkapoor90/This-is-Clickbait#3]
Text on pop-over should say "Not Clickbait." Clickbait is a mass noun, not a count noun so "a clickbait" makes no sense.

Cool plugin though!

**Comment by rahulkapoor90** [comment]
Sorry about that. I'll change that. 👍

**Comment by rahulkapoor90** [comment]
@MichaelSynnott Update released. Thanks for creating an issue.
